# Generated by Django 3.2.7 on 2021-09-03 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_hash', models.JSONField(default=dict)),
                ('map_n', models.IntegerField()),
                ('map_m', models.IntegerField()),
                ('map_image', models.ImageField(null=True, upload_to='maps')),
            ],
        ),
        migrations.CreateModel(
            name='MapLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premade_map_hash', models.JSONField(default=dict)),
                ('premade_map_n', models.IntegerField()),
                ('premade_map_m', models.IntegerField()),
                ('premade_map_image', models.ImageField(null=True, upload_to='maps')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInLobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_Plobby', models.IntegerField(default=0)),
                ('fortune_Plobby', models.IntegerField(default=1000)),
                ('returned_sync_Plobby', models.IntegerField(default=-1)),
                ('random_sync_plobby', models.IntegerField(default=-1)),
                ('player_Plobby', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_move_i', models.IntegerField(null=True)),
                ('last_move_j', models.IntegerField(null=True)),
                ('last_move_act', models.IntegerField(choices=[(1, 'up'), (2, 'right'), (3, 'down'), (4, 'left')], null=True)),
                ('map_layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobby.gamemap')),
                ('player_1_lobby', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lobby.playerinlobby')),
                ('player_2_lobby', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lobby.playerinlobby')),
            ],
        ),
    ]
