# Generated by Django 3.2.7 on 2021-09-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerinlobby',
            old_name='random_sync_plobby',
            new_name='epoch_sync_num_plobby',
        ),
    ]
