# Generated by Django 3.2.7 on 2021-09-29 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0002_rename_random_sync_plobby_playerinlobby_epoch_sync_num_plobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='last_move_player',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lobby.playerinlobby'),
        ),
    ]
