# Generated by Django 3.2.7 on 2021-09-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='color_profile',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
